packages:
  - packages/*
  - testcases/*
catalog:
  '@vitest/browser': ^3.1.4
  '@vitest/coverage-istanbul': ^3.1.4
  '@vitest/coverage-v8': ^3.1.4
  '@vitest/expect': ^3.1.4
  vite: ^6.3.6
  vitest: ^3.1.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
ignoredBuiltDependencies:
  - edgedriver
  - geckodriver
  - msw
