packages:
  - packages/*
  - testcases/*

catalog:
  '@storybook-community/storybook-dark-mode': ^7.0.3
  '@repobuddy/storybook': ^2.1.2
  '@repobuddy/vitest': ^2.0.0
  '@storybook/addon-a11y': ^10.0.8
  '@storybook/addon-docs': ^10.0.8
  '@storybook/addon-themes': ^10.0.8
  '@storybook/addon-vitest': ^10.0.8
  '@storybook/react-vite': ^10.0.8
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/browser': ^4.0.9
  '@vitest/browser-playwright': ^4.0.9
  '@vitest/browser-webdriverio': ^4.0.9
  '@vitest/coverage-istanbul': ^4.0.9
  '@vitest/coverage-v8': ^4.0.9
  '@vitest/expect': ^4.0.9
  storybook: ^10.0.8
  typescript: ^5.9.3
  vite: ^7.1.12
  vitest: ^4.0.9
  vitest-browser-react: ^2.0.2

ignoredBuiltDependencies:
  - edgedriver
  - geckodriver
  - msw

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
