packages:
  - packages/*
  - testcases/*

catalog:
  '@vitest/browser': ^4.0.0
  '@vitest/coverage-istanbul': ^4.0.3
  '@vitest/coverage-v8': ^4.0.0
  '@vitest/expect': ^4.0.6
  vite: ^7.1.12
  vitest: ^4.0.0

ignoredBuiltDependencies:
  - edgedriver
  - geckodriver
  - msw

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
