packages:
  - packages/*
  - testcases/*

catalog:
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-istanbul': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/expect': ^4.0.3
  vite: ^7.1.12
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - edgedriver
  - geckodriver
  - msw

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
