packages:
  - packages/*
  - testcases/*

catalog:
  '@vitest/browser': ^4.0.9
  '@vitest/browser-playwright': ^4.0.9
  '@vitest/browser-webdriverio': ^4.0.9
  '@vitest/coverage-istanbul': ^4.0.9
  '@vitest/coverage-v8': ^4.0.9
  '@vitest/expect': ^4.0.9
  vite: ^7.1.12
  vitest: ^4.0.9

ignoredBuiltDependencies:
  - edgedriver
  - geckodriver
  - msw

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
